[general]
flatpak_remote = "flathub"
bubblewrap_level = 3

[[repositories]]
name = "official"
index_url = "https://raw.githubusercontent.com/PaganLinux/pagan-repo/main/index.json"
base_url = "https://raw.githubusercontent.com/PaganLinux/pagan-repo/main"
