#!/usr/bin/env python3
"""Generate pagbuild files for all packages in the pagports tree."""

import os

BASE = "/workspaces/pag/examples/pagports/main"

PACKAGES = {
    # === CORE SYSTEM ===
    "glibc": {
        "ver": "2.40", "rel": 0,
        "desc": "GNU C Library",
        "url": "https://www.gnu.org/software/libc/",
        "license": "LGPL-2.1-or-later",
        "makedeps": "bison gcc make linux-headers",
        "deps": "",
        "sub": "glibc-dev glibc-locales glibc-utils",
        "source": "https://ftp.gnu.org/gnu/glibc/glibc-VER.tar.xz",
        "build": "mkdir -p build && cd build && ../configure --prefix=/usr --enable-stack-protector=strong && make",
        "package": "cd build && make DESTDIR=\"$pkgdir\" install",
    },
    "systemd": {
        "ver": "256.2", "rel": 0,
        "desc": "System and service manager",
        "url": "https://systemd.io/",
        "license": "LGPL-2.1-or-later",
        "makedeps": "meson ninja gcc gperf libcap-dev libmount-dev",
        "deps": "dbus libcap util-linux",
        "sub": "systemd-dev systemd-udev systemd-homed systemd-boot",
        "source": "https://github.com/systemd/systemd/archive/vVER.tar.gz",
        "build": "meson setup build -Dprefix=/usr -Dsysvinit-path= -Defi=false && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "dbus": {
        "ver": "1.14.10", "rel": 0,
        "desc": "D-Bus message bus system",
        "url": "https://www.freedesktop.org/wiki/Software/dbus/",
        "license": "AFL-2.1 OR GPL-2.0-or-later",
        "makedeps": "meson ninja gcc expat-dev",
        "deps": "",
        "sub": "dbus-dev dbus-x11 dbus-doc",
        "source": "https://dbus.freedesktop.org/releases/dbus/dbus-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "mesa": {
        "ver": "24.2.0", "rel": 0,
        "desc": "Mesa 3D Graphics Library",
        "url": "https://www.mesa3d.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc llvm-dev libdrm-dev wayland-protocols libx11-dev libxext-dev libxfixes-dev libxrandr-dev libxxf86vm-dev zlib-dev expat-dev python3-mako",
        "deps": "libdrm wayland libx11 libxext libxfixes libxrandr zlib",
        "sub": "mesa-dev mesa-dri mesa-egl mesa-gbm mesa-gl mesa-vulkan",
        "source": "https://archive.mesa3d.org/mesa-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr -Dgallium-drivers=iris,crocus,zink,llvmpipe -Dvulkan-drivers=intel,amd,swrast -Dplatforms=x11,wayland && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "libdrm": {
        "ver": "2.4.122", "rel": 0,
        "desc": "Direct Rendering Manager library",
        "url": "https://gitlab.freedesktop.org/mesa/drm",
        "license": "MIT",
        "makedeps": "meson ninja gcc",
        "deps": "",
        "sub": "libdrm-dev",
        "source": "https://dri.freedesktop.org/libdrm/libdrm-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "vulkan-loader": {
        "ver": "1.3.280", "rel": 0,
        "desc": "Vulkan Loader",
        "url": "https://github.com/KhronosGroup/Vulkan-Loader",
        "license": "Apache-2.0",
        "makedeps": "cmake gcc make python3 vulkan-headers",
        "deps": "vulkan-headers libx11 libxcb wayland",
        "sub": "vulkan-loader-dev",
        "source": "https://github.com/KhronosGroup/Vulkan-Loader/archive/vVER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "vulkan-headers": {
        "ver": "1.3.280", "rel": 0,
        "desc": "Vulkan Header files",
        "url": "https://github.com/KhronosGroup/Vulkan-Headers",
        "license": "Apache-2.0",
        "makedeps": "cmake gcc make",
        "deps": "",
        "sub": "",
        "source": "https://github.com/KhronosGroup/Vulkan-Headers/archive/vVER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "libinput": {
        "ver": "1.26.0", "rel": 0,
        "desc": "Input device library",
        "url": "https://gitlab.freedesktop.org/libinput/libinput",
        "license": "MIT",
        "makedeps": "meson ninja gcc libevdev-dev mtdev-dev",
        "deps": "libevdev mtdev",
        "sub": "libinput-dev",
        "source": "https://gitlab.freedesktop.org/libinput/libinput/-/archive/VER/libinput-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "libevdev": {
        "ver": "1.13.2", "rel": 0,
        "desc": "Event device library",
        "url": "https://gitlab.freedesktop.org/libevdev/libevdev",
        "license": "MIT",
        "makedeps": "meson ninja gcc",
        "deps": "",
        "sub": "libevdev-dev",
        "source": "https://gitlab.freedesktop.org/libevdev/libevdev/-/archive/VER/libevdev-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },

    # === FONTS & RENDERING ===
    "freetype": {
        "ver": "2.13.2", "rel": 0,
        "desc": "FreeType font rendering library",
        "url": "https://freetype.org/",
        "license": "FTL OR GPL-2.0-or-later",
        "makedeps": "meson ninja gcc libpng-dev",
        "deps": "libpng",
        "sub": "freetype-dev",
        "source": "https://download.savannah.gnu.org/releases/freetype/freetype-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr -Ddefault_library=shared && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "fontconfig": {
        "ver": "2.15.0", "rel": 0,
        "desc": "Font configuration library",
        "url": "https://www.freedesktop.org/wiki/Software/fontconfig/",
        "license": "MIT",
        "makedeps": "meson ninja gcc freetype-dev expat-dev",
        "deps": "freetype expat",
        "sub": "fontconfig-dev",
        "source": "https://www.freedesktop.org/software/fontconfig/release/fontconfig-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "harfbuzz": {
        "ver": "9.0.0", "rel": 0,
        "desc": "Text shaping library",
        "url": "https://harfbuzz.github.io/",
        "license": "MIT",
        "makedeps": "meson ninja gcc freetype-dev",
        "deps": "freetype",
        "sub": "harfbuzz-dev harfbuzz-icu",
        "source": "https://github.com/harfbuzz/harfbuzz/archive/VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "cairo": {
        "ver": "1.18.0", "rel": 0,
        "desc": "2D graphics library",
        "url": "https://cairographics.org/",
        "license": "LGPL-2.1-only OR MPL-1.1",
        "makedeps": "meson ninja gcc pixman-dev libpng-dev freetype-dev fontconfig-dev",
        "deps": "pixman libpng freetype fontconfig",
        "sub": "cairo-dev cairo-gobject",
        "source": "https://cairographics.org/releases/cairo-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "pango": {
        "ver": "1.54.0", "rel": 0,
        "desc": "Text layout and rendering library",
        "url": "https://pango.gnome.org/",
        "license": "LGPL-2.1-or-later",
        "makedeps": "meson ninja gcc cairo-dev harfbuzz-dev",
        "deps": "cairo harfbuzz fribidi",
        "sub": "pango-dev",
        "source": "https://download.gnome.org/sources/pango/1.54/pango-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },

    # === WAYLAND ===
    "wayland": {
        "ver": "1.23.0", "rel": 0,
        "desc": "Wayland display protocol",
        "url": "https://wayland.freedesktop.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc expat-dev libxml2-dev",
        "deps": "expat libxml2",
        "sub": "wayland-dev wayland-doc",
        "source": "https://gitlab.freedesktop.org/wayland/wayland/-/releases/VER/downloads/wayland-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr -Ddocumentation=false && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "wayland-protocols": {
        "ver": "1.36", "rel": 0,
        "desc": "Wayland protocol definitions",
        "url": "https://wayland.freedesktop.org/",
        "license": "MIT",
        "makedeps": "meson ninja wayland-dev",
        "deps": "wayland",
        "sub": "",
        "source": "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/VER/downloads/wayland-protocols-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "wlroots": {
        "ver": "0.18.0", "rel": 0,
        "desc": "Modular Wayland compositor library",
        "url": "https://gitlab.freedesktop.org/wlroots/wlroots",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev wayland-protocols libinput-dev mesa-dev libx11-dev libxcb-dev pixman-dev",
        "deps": "wayland wayland-protocols libinput mesa libx11 libxcb pixman",
        "sub": "wlroots-dev",
        "source": "https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/VER/wlroots-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr -Dexamples=false && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "sway": {
        "ver": "1.9", "rel": 0,
        "desc": "i3-compatible Wayland compositor",
        "url": "https://swaywm.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc wlroots-dev wayland-protocols json-c-dev pango-dev cairo-dev",
        "deps": "wlroots wayland json-c pango cairo swaybg",
        "sub": "sway-doc",
        "source": "https://github.com/swaywm/sway/archive/VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "hyprland": {
        "ver": "0.42.0", "rel": 0,
        "desc": "Dynamic tiling Wayland compositor",
        "url": "https://hyprland.org/",
        "license": "BSD-3-Clause",
        "makedeps": "cmake gcc make pkgconfig wayland-dev wayland-protocols libinput-dev mesa-dev libxcb-dev pango-dev cairo-dev hyprlang-dev hyprcursor-dev hyprgraphics-dev hyprutils-dev aquamarine-dev",
        "deps": "wayland libinput mesa libxcb pango cairo hyprlang hyprcursor hyprgraphics hyprutils aquamarine",
        "sub": "",
        "source": "https://github.com/hyprwm/Hyprland/archive/vVER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },

    # === X11 ===
    "libx11": {
        "ver": "1.8.9", "rel": 0,
        "desc": "X11 client-side library",
        "url": "https://www.x.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc xorgproto libxcb-dev",
        "deps": "xorgproto libxcb",
        "sub": "libx11-dev",
        "source": "https://www.x.org/releases/individual/lib/libX11-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "libxcb": {
        "ver": "1.17.0", "rel": 0,
        "desc": "X protocol C-language Binding",
        "url": "https://xcb.freedesktop.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc xcb-proto libxau-dev",
        "deps": "xcb-proto libxau",
        "sub": "libxcb-dev",
        "source": "https://xorg.freedesktop.org/archive/individual/lib/libxcb-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "xorgproto": {
        "ver": "2024.1", "rel": 0,
        "desc": "X.Org combined protocol headers",
        "url": "https://xorg.freedesktop.org/",
        "license": "MIT",
        "makedeps": "meson ninja",
        "deps": "",
        "sub": "",
        "source": "https://xorg.freedesktop.org/archive/individual/proto/xorgproto-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "xorg-server": {
        "ver": "21.1.13", "rel": 0,
        "desc": "X.Org X server",
        "url": "https://www.x.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc xorgproto libx11-dev libxext-dev libxrender-dev libxrandr-dev libxfixes-dev libxi-dev libxtst-dev libxdamage-dev libxcomposite-dev mesa-dev libdrm-dev pixman-dev",
        "deps": "xorgproto libx11 libxext libxrender libxrandr libxfixes libxi libxtst libxdamage libxcomposite mesa libdrm pixman",
        "sub": "xorg-server-dev xorg-server-xwayland",
        "source": "https://www.x.org/releases/individual/xserver/xorg-server-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr -Dxwayland=true && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "xwayland": {
        "ver": "24.1.0", "rel": 0,
        "desc": "X server for Wayland",
        "url": "https://wayland.freedesktop.org/xserver.html",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev wayland-protocols mesa-dev libdrm-dev pixman-dev xorgproto",
        "deps": "wayland mesa libdrm pixman xorgproto",
        "sub": "",
        "source": "https://gitlab.freedesktop.org/xorg/xserver/-/archive/xwayland-VER/xserver-xwayland-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },

    # === QT6 / KDE ===
    "qt6-base": {
        "ver": "6.7.2", "rel": 0,
        "desc": "Qt6 base libraries",
        "url": "https://www.qt.io/",
        "license": "LGPL-3.0-only OR GPL-3.0-only",
        "makedeps": "cmake gcc make ninja mesa-dev libx11-dev libxcb-dev libxext-dev libxrender-dev libxrandr-dev libxi-dev fontconfig-dev freetype-dev harfbuzz-dev pango-dev dbus-dev openssl-dev",
        "deps": "mesa libx11 libxcb libxext fontconfig freetype harfbuzz pango dbus openssl",
        "sub": "qt6-base-dev qt6-base-mysql qt6-base-postgresql",
        "source": "https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtbase-everywhere-src-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DFEATURE_system_zlib=ON && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "qt6-wayland": {
        "ver": "6.7.2", "rel": 0,
        "desc": "Qt6 Wayland integration",
        "url": "https://www.qt.io/",
        "license": "LGPL-3.0-only OR GPL-3.0-only",
        "makedeps": "cmake gcc make ninja qt6-base-dev wayland-dev wayland-protocols",
        "deps": "qt6-base wayland",
        "sub": "",
        "source": "https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtwayland-everywhere-src-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "kwin": {
        "ver": "6.1.3", "rel": 0,
        "desc": "KDE Window Manager",
        "url": "https://kde.org/plasma-desktop/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev qt6-wayland-dev mesa-dev wayland-dev wayland-protocols libx11-dev libxcb-dev libinput-dev",
        "deps": "qt6-base qt6-wayland mesa wayland libx11 libxcb libinput",
        "sub": "kwin-dev",
        "source": "https://download.kde.org/stable/plasma/6.1.3/kwin-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "plasma-workspace": {
        "ver": "6.1.3", "rel": 0,
        "desc": "KDE Plasma Workspace",
        "url": "https://kde.org/plasma-desktop/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev qt6-declarative-dev kwin-dev mesa-dev wayland-dev",
        "deps": "qt6-base qt6-declarative kwin mesa wayland",
        "sub": "plasma-workspace-dev",
        "source": "https://download.kde.org/stable/plasma/6.1.3/plasma-workspace-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "plasma-desktop": {
        "ver": "6.1.3", "rel": 0,
        "desc": "KDE Plasma Desktop",
        "url": "https://kde.org/plasma-desktop/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev plasma-workspace-dev",
        "deps": "qt6-base plasma-workspace",
        "sub": "",
        "source": "https://download.kde.org/stable/plasma/6.1.3/plasma-desktop-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },

    # === KDE APPS ===
    "dolphin": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE File Manager",
        "url": "https://apps.kde.org/dolphin/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base kio",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/dolphin-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "konsole": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Terminal Emulator",
        "url": "https://konsole.kde.org/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/konsole-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "gwenview": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Image Viewer",
        "url": "https://apps.kde.org/gwenview/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base kio",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/gwenview-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "okular": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Document Viewer",
        "url": "https://okular.kde.org/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/okular-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "spectacle": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Screenshot Tool",
        "url": "https://apps.kde.org/spectacle/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/spectacle-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "kate": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Advanced Text Editor",
        "url": "https://kate-editor.org/",
        "license": "LGPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/kate-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "ark": {
        "ver": "24.05.2", "rel": 0,
        "desc": "KDE Archiving Tool",
        "url": "https://apps.kde.org/ark/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/release-service/24.05.2/src/ark-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },

    # === AUDIO ===
    "pipewire": {
        "ver": "1.2.1", "rel": 0,
        "desc": "Multimedia processing graph",
        "url": "https://pipewire.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc dbus-dev",
        "deps": "dbus",
        "sub": "pipewire-dev pipewire-pulse pipewire-jack",
        "source": "https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/VER/pipewire-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr -Dsession-managers=[] && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "wireplumber": {
        "ver": "0.5.5", "rel": 0,
        "desc": "PipeWire session manager",
        "url": "https://pipewire.org/",
        "license": "MIT",
        "makedeps": "meson ninja gcc pipewire-dev",
        "deps": "pipewire",
        "sub": "",
        "source": "https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/VER/wireplumber-VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },

    # === DESKTOP APPS ===
    "firefox": {
        "ver": "130.0", "rel": 0,
        "desc": "Mozilla Firefox web browser",
        "url": "https://www.mozilla.org/firefox/",
        "license": "MPL-2.0",
        "makedeps": "rust cargo nodejs gcc make nasm yasm mesa-dev libx11-dev libxcb-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev dbus-dev gtk+3.0-dev pulseaudio-dev",
        "deps": "mesa libx11 libxcb libxext libxrender libxrandr dbus gtk+3.0 pulseaudio nss",
        "sub": "",
        "source": "https://ftp.mozilla.org/pub/firefox/releases/VER/source/firefox-VER.source.tar.xz",
        "build": "./mach build",
        "package": "./mach install",
    },
    "thunderbird": {
        "ver": "128.0", "rel": 0,
        "desc": "Mozilla Thunderbird email client",
        "url": "https://www.thunderbird.net/",
        "license": "MPL-2.0",
        "makedeps": "rust cargo nodejs gcc make mesa-dev libx11-dev dbus-dev gtk+3.0-dev",
        "deps": "mesa libx11 dbus gtk+3.0 nss",
        "sub": "",
        "source": "https://ftp.mozilla.org/pub/thunderbird/releases/VER/source/thunderbird-VER.source.tar.xz",
        "build": "./mach build",
        "package": "./mach install",
    },
    "chromium": {
        "ver": "128.0.6613.84", "rel": 0,
        "desc": "Chromium web browser",
        "url": "https://www.chromium.org/",
        "license": "BSD-3-Clause",
        "makedeps": "rust cargo nodejs gcc make ninja python3 mesa-dev libx11-dev libxcb-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev dbus-dev gtk+3.0-dev nss-dev",
        "deps": "mesa libx11 libxcb libxext libxrender libxrandr dbus gtk+3.0 nss",
        "sub": "",
        "source": "https://commondatastorage.googleapis.com/chromium-browser-official/chromium-VER.tar.xz",
        "build": "gn gen out/Release && ninja -C out/Release chrome",
        "package": "install -Dm755 out/Release/chrome \"$pkgdir\"/usr/bin/chromium",
    },
    "libreoffice": {
        "ver": "24.8.0", "rel": 0,
        "desc": "LibreOffice productivity suite",
        "url": "https://www.libreoffice.org/",
        "license": "MPL-2.0",
        "makedeps": "gcc make java-jdk perl python3 gtk+3.0-dev",
        "deps": "gtk+3.0 java-jre",
        "sub": "libreoffice-calc libreoffice-writer libreoffice-impress",
        "source": "https://download.documentfoundation.org/libreoffice/src/24.8.0/libreoffice-VER.tar.xz",
        "build": "./autogen.sh --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "gimp": {
        "ver": "2.10.38", "rel": 0,
        "desc": "GNU Image Manipulation Program",
        "url": "https://www.gimp.org/",
        "license": "GPL-3.0-or-later",
        "makedeps": "gcc make gtk+2.0-dev",
        "deps": "gtk+2.0",
        "sub": "",
        "source": "https://download.gimp.org/pub/gimp/v2.10/gimp-VER.tar.xz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "inkscape": {
        "ver": "1.3.2", "rel": 0,
        "desc": "Vector graphics editor",
        "url": "https://inkscape.org/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make gtk+3.0-dev",
        "deps": "gtk+3.0",
        "sub": "",
        "source": "https://inkscape.org/gallery/item/44616/inkscape-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "vlc": {
        "ver": "3.0.21", "rel": 0,
        "desc": "VLC media player",
        "url": "https://www.videolan.org/vlc/",
        "license": "GPL-2.0-or-later",
        "makedeps": "gcc make qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.videolan.org/vlc/3.0.21/vlc-VER.tar.xz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "mpv": {
        "ver": "0.38.0", "rel": 0,
        "desc": "Media player based on MPlayer",
        "url": "https://mpv.io/",
        "license": "GPL-2.0-or-later",
        "makedeps": "meson ninja gcc ffmpeg-dev mesa-dev wayland-dev libx11-dev",
        "deps": "ffmpeg mesa wayland libx11",
        "sub": "",
        "source": "https://github.com/mpv-player/mpv/archive/vVER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "ffmpeg": {
        "ver": "7.0.1", "rel": 0,
        "desc": "Complete multimedia framework",
        "url": "https://ffmpeg.org/",
        "license": "GPL-3.0-or-later",
        "makedeps": "gcc make nasm yasm",
        "deps": "",
        "sub": "ffmpeg-dev ffmpeg-libs",
        "source": "https://ffmpeg.org/releases/ffmpeg-VER.tar.xz",
        "build": "./configure --prefix=/usr --enable-shared && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },

    # === WAYLAND UTILS ===
    "grim": {
        "ver": "1.4.1", "rel": 0,
        "desc": "Grab images from Wayland compositor",
        "url": "https://sr.ht/~emersion/grim/",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev wayland-protocols",
        "deps": "wayland",
        "sub": "",
        "source": "https://git.sr.ht/~emersion/grim/archive/vVER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "slurp": {
        "ver": "1.5.0", "rel": 0,
        "desc": "Select a region in Wayland compositor",
        "url": "https://github.com/emersion/slurp",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev cairo-dev",
        "deps": "wayland cairo",
        "sub": "",
        "source": "https://github.com/emersion/slurp/archive/vVER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "waybar": {
        "ver": "0.10.4", "rel": 0,
        "desc": "Highly customizable Wayland bar",
        "url": "https://github.com/Alexays/Waybar",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev gtk+3.0-dev jsoncpp-dev",
        "deps": "wayland gtk+3.0 jsoncpp",
        "sub": "",
        "source": "https://github.com/Alexays/Waybar/archive/VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "wofi": {
        "ver": "1.4.1", "rel": 0,
        "desc": "Launcher/menu for wlroots compositors",
        "url": "https://hg.sr.ht/~scoopta/wofi",
        "license": "GPL-3.0-or-later",
        "makedeps": "meson ninja gcc wayland-dev gtk+3.0-dev",
        "deps": "wayland gtk+3.0",
        "sub": "",
        "source": "https://hg.sr.ht/~scoopta/wofi/archive/vVER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "foot": {
        "ver": "1.18.1", "rel": 0,
        "desc": "Fast, lightweight Wayland terminal",
        "url": "https://codeberg.org/dnkl/foot",
        "license": "MIT",
        "makedeps": "meson ninja gcc wayland-dev wayland-protocols pixman-dev fontconfig-dev",
        "deps": "wayland pixman fontconfig",
        "sub": "foot-terminfo",
        "source": "https://codeberg.org/dnkl/foot/archive/VER.tar.gz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "alacritty": {
        "ver": "0.13.2", "rel": 0,
        "desc": "GPU-accelerated terminal emulator",
        "url": "https://alacritty.org/",
        "license": "Apache-2.0",
        "makedeps": "rust cargo cmake gcc make fontconfig-dev",
        "deps": "fontconfig",
        "sub": "",
        "source": "https://github.com/alacritty/alacritty/archive/vVER.tar.gz",
        "build": "cargo build --release",
        "package": "install -Dm755 target/release/alacritty \"$pkgdir\"/usr/bin/alacritty",
    },

    # === DISPLAY MANAGERS ===
    "sddm": {
        "ver": "0.21.0", "rel": 0,
        "desc": "QML-based display manager",
        "url": "https://github.com/sddm/sddm",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make qt6-base-dev qt6-declarative-dev",
        "deps": "qt6-base qt6-declarative",
        "sub": "",
        "source": "https://github.com/sddm/sddm/archive/vVER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },

    # === DEV TOOLS ===
    "gcc": {
        "ver": "14.2.0", "rel": 0,
        "desc": "GNU Compiler Collection",
        "url": "https://gcc.gnu.org/",
        "license": "GPL-3.0-or-later",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "gcc-g++ gcc-fortran gcc-objc",
        "source": "https://ftp.gnu.org/gnu/gcc/gcc-VER/gcc-VER.tar.xz",
        "build": "./configure --prefix=/usr --enable-languages=c,c++ && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "llvm": {
        "ver": "18.1.8", "rel": 0,
        "desc": "LLVM compiler infrastructure",
        "url": "https://llvm.org/",
        "license": "Apache-2.0",
        "makedeps": "cmake gcc make ninja python3",
        "deps": "",
        "sub": "llvm-dev llvm-libs clang lld",
        "source": "https://github.com/llvm/llvm-project/archive/llvmorg-VER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_ENABLE_PROJECTS=clang && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "rust": {
        "ver": "1.82.0", "rel": 0,
        "desc": "Rust programming language",
        "url": "https://www.rust-lang.org/",
        "license": "MIT OR Apache-2.0",
        "makedeps": "gcc make cmake curl",
        "deps": "gcc",
        "sub": "rust-doc rust-src",
        "source": "https://static.rust-lang.org/dist/rustc-VER-src.tar.gz",
        "build": "./x.py build",
        "package": "./x.py install",
    },
    "python3": {
        "ver": "3.12.5", "rel": 0,
        "desc": "Python programming language",
        "url": "https://www.python.org/",
        "license": "PSF-2.0",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "python3-dev python3-doc",
        "source": "https://www.python.org/ftp/python/VER/Python-VER.tar.xz",
        "build": "./configure --prefix=/usr --enable-shared && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "nodejs": {
        "ver": "22.7.0", "rel": 0,
        "desc": "Node.js JavaScript runtime",
        "url": "https://nodejs.org/",
        "license": "MIT",
        "makedeps": "gcc make python3",
        "deps": "",
        "sub": "nodejs-dev nodejs-npm",
        "source": "https://nodejs.org/dist/vVER/node-vVER.tar.xz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "go": {
        "ver": "1.23.0", "rel": 0,
        "desc": "Go programming language",
        "url": "https://go.dev/",
        "license": "BSD-3-Clause",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "go-doc",
        "source": "https://go.dev/dl/goVER.src.tar.gz",
        "build": "cd src && ./make.bash",
        "package": "cp -a bin \"$pkgdir\"/usr/",
    },
    "cmake": {
        "ver": "3.30.2", "rel": 0,
        "desc": "Cross-platform build system",
        "url": "https://cmake.org/",
        "license": "BSD-3-Clause",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "",
        "source": "https://github.com/Kitware/CMake/archive/vVER.tar.gz",
        "build": "./bootstrap --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "meson": {
        "ver": "1.5.1", "rel": 0,
        "desc": "Meson build system",
        "url": "https://mesonbuild.com/",
        "license": "Apache-2.0",
        "makedeps": "python3",
        "deps": "python3 ninja",
        "sub": "",
        "source": "https://github.com/mesonbuild/meson/archive/VER.tar.gz",
        "build": "python3 setup.py build",
        "package": "python3 setup.py install --root=\"$pkgdir\"",
    },

    # === NETWORKING ===
    "networkmanager": {
        "ver": "1.48.2", "rel": 0,
        "desc": "Network connection manager",
        "url": "https://networkmanager.dev/",
        "license": "GPL-2.0-or-later",
        "makedeps": "meson ninja gcc dbus-dev",
        "deps": "dbus iwd",
        "sub": "networkmanager-dev networkmanager-wifi",
        "source": "https://download.gnome.org/sources/NetworkManager/1.48/NetworkManager-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "openssh": {
        "ver": "9.8p1", "rel": 0,
        "desc": "OpenSSH client and server",
        "url": "https://www.openssh.com/",
        "license": "BSD",
        "makedeps": "gcc make",
        "deps": "openssl",
        "sub": "openssh-server openssh-client",
        "source": "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-VER.tar.gz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },

    # === SHELL TOOLS ===
    "bash": {
        "ver": "5.2.32", "rel": 0,
        "desc": "GNU Bourne Again Shell",
        "url": "https://www.gnu.org/software/bash/",
        "license": "GPL-3.0-or-later",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "bash-doc bash-completion",
        "source": "https://ftp.gnu.org/gnu/bash/bash-VER.tar.gz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "zsh": {
        "ver": "5.9", "rel": 0,
        "desc": "Z shell",
        "url": "https://www.zsh.org/",
        "license": "MIT",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "zsh-doc",
        "source": "https://sourceforge.net/projects/zsh/files/zsh/VER/zsh-VER.tar.xz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "tmux": {
        "ver": "3.4", "rel": 0,
        "desc": "Terminal multiplexer",
        "url": "https://github.com/tmux/tmux",
        "license": "ISC",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "",
        "source": "https://github.com/tmux/tmux/releases/download/VER/tmux-VER.tar.gz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "neovim": {
        "ver": "0.10.1", "rel": 0,
        "desc": "Hyperextensible Vim-based text editor",
        "url": "https://neovim.io/",
        "license": "Apache-2.0",
        "makedeps": "cmake gcc make ninja",
        "deps": "",
        "sub": "",
        "source": "https://github.com/neovim/neovim/archive/vVER.tar.gz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "htop": {
        "ver": "3.3.0", "rel": 0,
        "desc": "Interactive process viewer",
        "url": "https://htop.dev/",
        "license": "GPL-2.0-or-later",
        "makedeps": "gcc make",
        "deps": "",
        "sub": "",
        "source": "https://github.com/htop-dev/htop/archive/VER.tar.gz",
        "build": "./autogen.sh && ./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },
    "git": {
        "ver": "2.46.0", "rel": 0,
        "desc": "Distributed version control system",
        "url": "https://git-scm.com/",
        "license": "GPL-2.0-only",
        "makedeps": "gcc make curl-dev expat-dev",
        "deps": "curl expat",
        "sub": "git-doc git-bash-completion",
        "source": "https://mirrors.edge.kernel.org/pub/software/scm/git/git-VER.tar.xz",
        "build": "./configure --prefix=/usr && make",
        "package": "make DESTDIR=\"$pkgdir\" install",
    },

    # === FONTS & THEMES ===
    "noto-fonts": {
        "ver": "24.8.1", "rel": 0,
        "desc": "Noto fonts family",
        "url": "https://fonts.google.com/noto",
        "license": "OFL-1.1",
        "makedeps": "",
        "deps": "",
        "sub": "",
        "source": "https://github.com/notofonts/noto-fonts/archive/refs/tags/vVER.tar.gz",
        "build": "",
        "package": "mkdir -p \"$pkgdir\"/usr/share/fonts/noto && cp -a fonts/* \"$pkgdir\"/usr/share/fonts/noto/",
    },
    "adwaita-icon-theme": {
        "ver": "46.0", "rel": 0,
        "desc": "GNOME Adwaita icon theme",
        "url": "https://gitlab.gnome.org/GNOME/adwaita-icon-theme",
        "license": "LGPL-3.0-only OR CC-BY-SA-3.0",
        "makedeps": "meson ninja",
        "deps": "",
        "sub": "",
        "source": "https://download.gnome.org/sources/adwaita-icon-theme/46/adwaita-icon-theme-VER.tar.xz",
        "build": "meson setup build -Dprefix=/usr && ninja -C build",
        "package": "DESTDIR=\"$pkgdir\" ninja -C build install",
    },
    "breeze": {
        "ver": "6.1.3", "rel": 0,
        "desc": "KDE Breeze theme",
        "url": "https://kde.org/plasma-desktop/",
        "license": "GPL-2.0-or-later",
        "makedeps": "cmake gcc make ninja qt6-base-dev",
        "deps": "qt6-base",
        "sub": "",
        "source": "https://download.kde.org/stable/plasma/6.1.3/breeze-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
    "breeze-icons": {
        "ver": "6.1.0", "rel": 0,
        "desc": "KDE Breeze icon theme",
        "url": "https://kde.org/",
        "license": "LGPL-3.0-only",
        "makedeps": "cmake gcc make ninja",
        "deps": "",
        "sub": "",
        "source": "https://download.kde.org/stable/frameworks/6.1.0/breeze-icons-VER.tar.xz",
        "build": "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build",
        "package": "cmake --install build --prefix=\"$pkgdir\"/usr",
    },
}

# ============================================================
def generate_pagbuild(name, info):
    ver = info["ver"]
    rel = info["rel"]
    desc = info["desc"]
    url = info["url"]
    lic = info["license"]
    makedeps = info["makedeps"]
    deps = info.get("deps", "")
    sub = info.get("sub", "")
    source = info["source"].replace("VER", ver)
    build = info["build"]
    package = info["package"]

    # Get maintainer if set
    maintainer = info.get("maintainer", "PaganLinux Team <team@paganlinux.eu>")

    lines = [
        f"# PaganLinux Build Script (pagbuild)",
        f"# {desc}",
        f"",
        f'maintainer="{maintainer}"',
        f'pkgname={name}',
        f'pkgver={ver}',
        f'pkgrel={rel}',
        f'pkgdesc="{desc}"',
        f'url="{url}"',
        f'arch="x86_64"',
        f'license="{lic}"',
    ]

    if makedeps:
        lines.append(f'makedepends="{makedeps}"')
    else:
        lines.append(f'makedepends=""')

    if deps:
        lines.append(f'depends="{deps}"')
    else:
        lines.append(f'depends=""')

    if sub:
        lines.append(f'subpackages="{sub}"')

    lines.append(f'source="{source}"')
    lines.append(f'builddir="$srcdir"')
    lines.append("")

    if build:
        lines.append("build() {")
        lines.append(f"    {build}")
        lines.append("}")
        lines.append("")

    lines.append("package() {")
    lines.append(f"    {package}")
    lines.append("}")
    lines.append("")

    # sha512sums placeholder
    lines.append('# sha512sums=""')
    lines.append("")

    return "\n".join(lines)


def main():
    created = 0
    for name, info in PACKAGES.items():
        dirpath = os.path.join(BASE, name)
        os.makedirs(dirpath, exist_ok=True)
        filepath = os.path.join(dirpath, "pagbuild")
        content = generate_pagbuild(name, info)
        with open(filepath, "w") as f:
            f.write(content)
        created += 1

    print(f"Created {created} pagbuild files in {BASE}/")

if __name__ == "__main__":
    main()
